on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  
  trigger_zip_builder:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: echoing GITHUB_TOKEN
      run: echo $GITHUB_TOKEN
    - name: triggering event
      run: | 
        curl \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GITHUB_TOKEN" \
        https://api.github.com/repos/Aspect13/performance_post_processor/dispatches \
        -d '{"event_type":"make_zip", "client_payload":{}}'
