on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  trigger_zip_builder:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
    - name: echoing TOKEN
      run: echo $TOKEN
    - name: triggering event
      run: | 
        curl \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $TOKEN" \
        https://api.github.com/repos/Aspect13/performance_post_processor/dispatches \
        -d '{"event_type":"make_zip", "client_payload":{}}'
